import type { Country } from '../types';

// 対応国データ
export const countries: Country[] = [
  {
    id: 'us',
    name: 'アメリカ',
    nameEn: 'United States',
    leader: '大統領',
    leaderEn: 'President',
    flag: '\u{1F1FA}\u{1F1F8}',
    accentColor: '#1a3a5c',
  },
  {
    id: 'cn',
    name: '中国',
    nameEn: 'China',
    leader: '国家主席',
    leaderEn: 'Chairman',
    flag: '\u{1F1E8}\u{1F1F3}',
    accentColor: '#c41e3a',
  },
  {
    id: 'ru',
    name: 'ロシア',
    nameEn: 'Russia',
    leader: '大統領',
    leaderEn: 'President',
    flag: '\u{1F1F7}\u{1F1FA}',
    accentColor: '#0039a6',
  },
  {
    id: 'uk',
    name: 'イギリス',
    nameEn: 'United Kingdom',
    leader: '首相',
    leaderEn: 'Prime Minister',
    flag: '\u{1F1EC}\u{1F1E7}',
    accentColor: '#003078',
  },
  {
    id: 'fr',
    name: 'フランス',
    nameEn: 'France',
    leader: '大統領',
    leaderEn: 'President',
    flag: '\u{1F1EB}\u{1F1F7}',
    accentColor: '#002395',
  },
  {
    id: 'de',
    name: 'ドイツ',
    nameEn: 'Germany',
    leader: '首相',
    leaderEn: 'Chancellor',
    flag: '\u{1F1E9}\u{1F1EA}',
    accentColor: '#dd0000',
  },
  {
    id: 'kr',
    name: '韓国',
    nameEn: 'South Korea',
    leader: '大統領',
    leaderEn: 'President',
    flag: '\u{1F1F0}\u{1F1F7}',
    accentColor: '#003478',
  },
  {
    id: 'sa',
    name: 'サウジアラビア',
    nameEn: 'Saudi Arabia',
    leader: '皇太子',
    leaderEn: 'Crown Prince',
    flag: '\u{1F1F8}\u{1F1E6}',
    accentColor: '#006c35',
  },
  {
    id: 'il',
    name: 'イスラエル',
    nameEn: 'Israel',
    leader: '首相',
    leaderEn: 'Prime Minister',
    flag: '\u{1F1EE}\u{1F1F1}',
    accentColor: '#0038b8',
  },
  {
    id: 'in',
    name: 'インド',
    nameEn: 'India',
    leader: '首相',
    leaderEn: 'Prime Minister',
    flag: '\u{1F1EE}\u{1F1F3}',
    accentColor: '#ff9933',
  },
];
